name: Github Actions Example

on:
  #In here we set up our workflow trigger. Pretty much whatever we put in this field determined
  #what will trigger the workflow to run
  
  pull_request:
  push:
    branches: [ "main" ]  
 # Here we are saying that on every pull request and every push to the following branches run the workflow

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

