name: Github Actions Example

#In here we set up our workflow trigger. Pretty much whatever we put in this field determined
  #what will trigger the workflow to run
on:
  push:
    branches:
      - main

jobs:
  print_hello:
    runs-on: ubuntu-latest 
    steps: # Steps represent a sequence of tasks that will be executed as part of the job
     - uses: actions/checkout@v3
     - name: Run a one line script
     - run: echo "Hello World!"

  
 

